remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
title: Mininet-Sec
description: Plataforma de experimentação para cibersegurança em redes programáveis
defaults:
  - scope:
      path: "pt-br"
    values:
      lang: "pt-br"
  - scope:
      path: "en"
    values:
      lang: "en"
